apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
    # No specific metadata needed for basic Kubernetes secret store
scopes:
  - tasks-service
  - api-gateway
  - notification-service
  - recurring-task-service
  - audit-service
  - websocket-service
